// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eryxaspppbuzxjekaith.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyeXhhc3BwcGJ1enhqZWthaXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NjQ1MTAsImV4cCI6MjA2NTA0MDUxMH0.ylItcHurzdkNdad5RnegFDziFiOLmRCM4a5LepH7_KI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);